### ISSUE TITLE
droidotter crashing on image selection (for upload)

### ISSUE THREAD

**Issue by deavmi** [pjuu/droidotter#6]
Whenever I try to upload an image in Droidotter and I select an image Droidotter then crashes.

**Comment by docapotamus** [comment]
From message on site with is Android 5.0.1.

**Comment by deavmi** [comment]
@pjuu Yep.

**Comment by deavmi** [comment]
@pjuu I had another issue that I might of mentioned to you before about the Upload picture button not appearing on my device, don't worry, I think taht is to do with my browser, I have JS disabled on it and it yeah, just is maybe persay an escoteric browser, idk. But I do not think that that was a general error.

**Comment by docapotamus** [comment]
@deavmi It does use some strange CSS to make it look like it does as file inputs are pretty bad for styling.

Can you please also let me know the device you are using?

**Comment by docapotamus** [comment]
Video of the bug: http://youtu.be/gPuPJmy7bss

Thanks

**Comment by docapotamus** [comment]
@Deavmi I'm struggling to emulate this crash via AVD.

Can you please see if you can locate a crash dump on your device? I am not seeing anything through the developer console because I guess you are running this from F-Droid?

**Comment by deavmi** [comment]
Yes from F-Droid. :D

**Comment by deavmi** [comment]
It's a pleasure. :D

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by deavmi** [comment]
**My device:** Samsung Galaxy Note 4 (Stock Samsung ROM)

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by docapotamus** [comment]
Hmmm... I know this may be a lot to ask but can you see if there is a crash dump located on your phone?

**Comment by docapotamus** [comment]
Hello @deavmi to fix this I am going to need the ANR reported via the play store or a copy the dump.

**Comment by deavmi** [comment]
Okay, where are dumps located?

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by docapotamus** [comment]
@deavmi `/data/anr/traces.txt` or `/data/tombstones` or just check `/data/anr`

**Comment by deavmi** [comment]
I need not to have root to access that right?

**Comment by deavmi** [comment]
Also is there any sensitive information that goes against my privacy within those crash dump files?

**Comment by deavmi** [comment]
I will get that file soon and publish it here. :smile:

**Comment by docapotamus** [comment]
@deavmi. I am not aware of any. If you go through the playstore then I get that file. Feel free to check them out first. If you are worried about it feel free to e-mail them to security@pjuu.com

**Comment by deavmi** [comment]
Okay. I will check for anything in those dumps that relates to my password. I will scan for those. Do a quick find/search and yeah. That's all that really worries me is my password. :S

**Comment by deavmi** [comment]
Pleasure :smile:

---

Sent from Deavmi
Keep on hacking...

Contact Deavmi via:

Pjuu: https://pjuu.com/deavmi
GNU Social: deavmi@quitter.se
Twitter: https://twitter.com/deavmi
Main mailbox: deavmi@openmailbox.org

**Comment by docapotamus** [comment]
@deavmi are you still having this issue? If so have you managed to locate the error file?

**Comment by deavmi** [comment]
Just tested the current version if Droidotter out and there is still a big when selecting an image for upload.

**Comment by docapotamus** [comment]
Is this on the same device?

**Comment by deavmi** [comment]
@docapotamus Yes.
